-- Esquema inicial de ArteMedica Farmacia.
--
-- Generado a partir del esquema que Hibernate venia creando con ddl-auto=update, para
-- congelarlo como punto de partida versionado. A partir de aqui todo cambio de esquema
-- viaja en una migracion nueva (V2, V3...) y nunca modificando este archivo: Flyway guarda
-- la suma de comprobacion de cada migracion ya aplicada y rechaza el arranque si cambia.
--
-- La aplicacion corre con ddl-auto=validate, asi que si las entidades y este esquema
-- divergen, el arranque falla en lugar de alterar la base de datos por su cuenta.

CREATE TABLE area (
    id bigint NOT NULL,
    activo boolean NOT NULL,
    descripcion character varying(255),
    nombre character varying(255) NOT NULL
);

ALTER TABLE area ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME area_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE categoria_medicamento (
    id bigint NOT NULL,
    activo boolean NOT NULL,
    descripcion character varying(255),
    nombre character varying(255) NOT NULL
);

ALTER TABLE categoria_medicamento ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME categoria_medicamento_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE codigo_equivalente (
    id bigint NOT NULL,
    activo boolean NOT NULL,
    codigo_barras character varying(255) NOT NULL,
    created_at timestamp(6) without time zone,
    created_by character varying(255),
    producto_id bigint NOT NULL
);

ALTER TABLE codigo_equivalente ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME codigo_equivalente_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE compra (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone,
    fecha_compra date NOT NULL,
    numero_factura character varying(255) NOT NULL,
    proveedor_id bigint NOT NULL,
    usuario_registro_id bigint NOT NULL
);

CREATE TABLE compra_detalle (
    id bigint NOT NULL,
    cantidad integer NOT NULL,
    costo_unitario numeric(38,2) NOT NULL,
    compra_id bigint NOT NULL,
    lote_id bigint,
    producto_id bigint NOT NULL
);

ALTER TABLE compra_detalle ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME compra_detalle_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE compra ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME compra_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE configuracion_sistema (
    id bigint NOT NULL,
    clave character varying(255) NOT NULL,
    descripcion character varying(255),
    updated_at timestamp(6) without time zone NOT NULL,
    updated_by character varying(255),
    valor character varying(255) NOT NULL
);

ALTER TABLE configuracion_sistema ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME configuracion_sistema_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE empleado (
    id bigint NOT NULL,
    activo boolean NOT NULL,
    apellido_materno character varying(255),
    apellido_paterno character varying(255) NOT NULL,
    cedula_profesional character varying(255),
    especialidad character varying(255),
    nombres character varying(255) NOT NULL,
    telefono_guardia character varying(255),
    tipo character varying(255) NOT NULL,
    CONSTRAINT empleado_tipo_check CHECK (((tipo)::text = ANY ((ARRAY['MEDICO'::character varying, 'FARMACEUTICO'::character varying, 'ADMIN'::character varying])::text[])))
);

ALTER TABLE empleado ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME empleado_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE lote (
    id bigint NOT NULL,
    activo boolean NOT NULL,
    cantidad_inicial integer NOT NULL,
    costo_compra numeric(38,2) NOT NULL,
    created_at timestamp(6) without time zone,
    existencia_actual integer NOT NULL,
    fecha_caducidad date NOT NULL,
    numero_lote character varying(255) NOT NULL,
    updated_at timestamp(6) without time zone,
    producto_id bigint NOT NULL,
    proveedor_id bigint NOT NULL
);

ALTER TABLE lote ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME lote_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE movimiento_inventario (
    id bigint NOT NULL,
    cantidad integer NOT NULL,
    fecha_movimiento timestamp(6) without time zone NOT NULL,
    motivo character varying(255),
    origen_id bigint,
    origen_tipo character varying(255) NOT NULL,
    saldo_resultante integer NOT NULL,
    tipo_movimiento character varying(255) NOT NULL,
    lote_id bigint NOT NULL,
    producto_id bigint NOT NULL,
    usuario_id bigint NOT NULL,
    CONSTRAINT movimiento_inventario_origen_tipo_check CHECK (((origen_tipo)::text = ANY ((ARRAY['COMPRA'::character varying, 'SOLICITUD'::character varying, 'MANUAL'::character varying])::text[]))),
    CONSTRAINT movimiento_inventario_tipo_movimiento_check CHECK (((tipo_movimiento)::text = ANY ((ARRAY['ENTRADA'::character varying, 'SALIDA'::character varying, 'MERMA'::character varying])::text[])))
);

ALTER TABLE movimiento_inventario ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME movimiento_inventario_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE producto (
    id bigint NOT NULL,
    activo boolean NOT NULL,
    codigo_barras character varying(255),
    es_controlado boolean NOT NULL,
    nombre character varying(255) NOT NULL,
    precio_compra numeric(38,2),
    precio_venta numeric(38,2),
    presentacion character varying(255) NOT NULL,
    stock_actual integer NOT NULL,
    stock_minimo integer NOT NULL,
    version bigint NOT NULL,
    categoria_id bigint NOT NULL
);

ALTER TABLE producto ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME producto_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE proveedor (
    id bigint NOT NULL,
    activo boolean NOT NULL,
    correo character varying(255),
    direccion character varying(255),
    nombre character varying(255) NOT NULL,
    telefono character varying(255)
);

ALTER TABLE proveedor ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME proveedor_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE solicitud (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone,
    estatus character varying(255) NOT NULL,
    fecha_aprobacion timestamp(6) without time zone,
    fecha_entrega timestamp(6) without time zone,
    fecha_solicitud timestamp(6) without time zone NOT NULL,
    motivo_cancelacion character varying(255),
    motivo_rechazo character varying(255),
    version bigint NOT NULL,
    area_id bigint NOT NULL,
    farmaceutico_id bigint,
    medico_id bigint NOT NULL,
    CONSTRAINT solicitud_estatus_check CHECK (((estatus)::text = ANY ((ARRAY['PENDIENTE'::character varying, 'APROBADO'::character varying, 'RECHAZADO'::character varying, 'CANCELADA'::character varying, 'ENTREGADA_PARCIAL'::character varying, 'ENTREGADA_COMPLETA'::character varying])::text[])))
);

CREATE TABLE solicitud_detalle (
    id bigint NOT NULL,
    cantidad_autorizada integer,
    cantidad_entregada integer NOT NULL,
    cantidad_solicitada integer NOT NULL,
    lote_id bigint,
    producto_id bigint NOT NULL,
    solicitud_id bigint NOT NULL
);

ALTER TABLE solicitud_detalle ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME solicitud_detalle_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE solicitud ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME solicitud_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE usuario (
    id bigint NOT NULL,
    activo boolean NOT NULL,
    created_at timestamp(6) without time zone,
    password character varying(255) NOT NULL,
    rol character varying(255) NOT NULL,
    updated_at timestamp(6) without time zone,
    username character varying(255) NOT NULL,
    empleado_id bigint NOT NULL,
    CONSTRAINT usuario_rol_check CHECK (((rol)::text = ANY ((ARRAY['ADMIN'::character varying, 'MEDICO'::character varying, 'FARMACEUTICO'::character varying])::text[])))
);

ALTER TABLE usuario ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME usuario_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY area
    ADD CONSTRAINT area_pkey PRIMARY KEY (id);

ALTER TABLE ONLY categoria_medicamento
    ADD CONSTRAINT categoria_medicamento_pkey PRIMARY KEY (id);

ALTER TABLE ONLY codigo_equivalente
    ADD CONSTRAINT codigo_equivalente_pkey PRIMARY KEY (id);

ALTER TABLE ONLY compra_detalle
    ADD CONSTRAINT compra_detalle_pkey PRIMARY KEY (id);

ALTER TABLE ONLY compra
    ADD CONSTRAINT compra_pkey PRIMARY KEY (id);

ALTER TABLE ONLY configuracion_sistema
    ADD CONSTRAINT configuracion_sistema_pkey PRIMARY KEY (id);

ALTER TABLE ONLY empleado
    ADD CONSTRAINT empleado_pkey PRIMARY KEY (id);

ALTER TABLE ONLY lote
    ADD CONSTRAINT lote_pkey PRIMARY KEY (id);

ALTER TABLE ONLY movimiento_inventario
    ADD CONSTRAINT movimiento_inventario_pkey PRIMARY KEY (id);

ALTER TABLE ONLY producto
    ADD CONSTRAINT producto_pkey PRIMARY KEY (id);

ALTER TABLE ONLY proveedor
    ADD CONSTRAINT proveedor_pkey PRIMARY KEY (id);

ALTER TABLE ONLY solicitud_detalle
    ADD CONSTRAINT solicitud_detalle_pkey PRIMARY KEY (id);

ALTER TABLE ONLY solicitud
    ADD CONSTRAINT solicitud_pkey PRIMARY KEY (id);

ALTER TABLE ONLY usuario
    ADD CONSTRAINT uk863n1y3x0jalatoir4325ehal UNIQUE (username);

ALTER TABLE ONLY configuracion_sistema
    ADD CONSTRAINT ukn2k8b6hwyumsdfmax8vg0320m UNIQUE (clave);

ALTER TABLE ONLY producto
    ADD CONSTRAINT uknrobij4fg0dpdfcro7t2ystd1 UNIQUE (codigo_barras);

ALTER TABLE ONLY usuario
    ADD CONSTRAINT usuario_pkey PRIMARY KEY (id);

ALTER TABLE ONLY lote
    ADD CONSTRAINT fk10w4ss32kjo5omy8hl4n5y4vw FOREIGN KEY (proveedor_id) REFERENCES proveedor(id);

ALTER TABLE ONLY solicitud_detalle
    ADD CONSTRAINT fk1b87ompg5ou5wv1xfjck3txs5 FOREIGN KEY (solicitud_id) REFERENCES solicitud(id);

ALTER TABLE ONLY compra_detalle
    ADD CONSTRAINT fk207xgpimejf3xg94dgi6ryx2f FOREIGN KEY (lote_id) REFERENCES lote(id);

ALTER TABLE ONLY compra
    ADD CONSTRAINT fk5rv6m306dgdn4cn14eyhpexwu FOREIGN KEY (proveedor_id) REFERENCES proveedor(id);

ALTER TABLE ONLY solicitud_detalle
    ADD CONSTRAINT fk6f6hj313nwxrfsn06f209v7k7 FOREIGN KEY (lote_id) REFERENCES lote(id);

ALTER TABLE ONLY solicitud
    ADD CONSTRAINT fk6uqiw1ganhpuc1go764c3r071 FOREIGN KEY (medico_id) REFERENCES empleado(id);

ALTER TABLE ONLY codigo_equivalente
    ADD CONSTRAINT fk8dv36c1mtcscy5phaendbc5r9 FOREIGN KEY (producto_id) REFERENCES producto(id);

ALTER TABLE ONLY solicitud
    ADD CONSTRAINT fk96je0ltm10bsp9773s3313t53 FOREIGN KEY (farmaceutico_id) REFERENCES empleado(id);

ALTER TABLE ONLY movimiento_inventario
    ADD CONSTRAINT fkd6bavqmj4o0mvn82ve46jac9v FOREIGN KEY (producto_id) REFERENCES producto(id);

ALTER TABLE ONLY compra_detalle
    ADD CONSTRAINT fkftb7g1gfco8vy0fpf53skcbny FOREIGN KEY (compra_id) REFERENCES compra(id);

ALTER TABLE ONLY solicitud_detalle
    ADD CONSTRAINT fkg849myp0km8pbu2kryafliw3h FOREIGN KEY (producto_id) REFERENCES producto(id);

ALTER TABLE ONLY solicitud
    ADD CONSTRAINT fkgbex95foj5ovc5252123uv5f9 FOREIGN KEY (area_id) REFERENCES area(id);

ALTER TABLE ONLY producto
    ADD CONSTRAINT fkgwix47yqnrqii8q2v0fbrdhw FOREIGN KEY (categoria_id) REFERENCES categoria_medicamento(id);

ALTER TABLE ONLY usuario
    ADD CONSTRAINT fkjn24nnj8w0mmt2eq54ol6xrq2 FOREIGN KEY (empleado_id) REFERENCES empleado(id);

ALTER TABLE ONLY lote
    ADD CONSTRAINT fkkbey6ru4bao4wteuecjibm9o3 FOREIGN KEY (producto_id) REFERENCES producto(id);

ALTER TABLE ONLY compra_detalle
    ADD CONSTRAINT fkmufkoh69y4dxk2ts2odtyr7gt FOREIGN KEY (producto_id) REFERENCES producto(id);

ALTER TABLE ONLY movimiento_inventario
    ADD CONSTRAINT fkprbti86kth7eb6duja2weque7 FOREIGN KEY (lote_id) REFERENCES lote(id);

ALTER TABLE ONLY compra
    ADD CONSTRAINT fkq2h5rrbintcslpeml5lduh2t0 FOREIGN KEY (usuario_registro_id) REFERENCES usuario(id);

ALTER TABLE ONLY movimiento_inventario
    ADD CONSTRAINT fkt6p6ejpbblav1phv0lgjpeg4r FOREIGN KEY (usuario_id) REFERENCES usuario(id);
