-- Refresh tokens: permiten renovar el access token JWT sin volver a pedir usuario/contraseña,
-- y permiten un logout real. Un JWT firmado no se puede invalidar antes de que expire, pero el
-- refresh token vive en esta tabla y sí se puede revocar (logout, o reuso sospechoso de un
-- token ya rotado). Nunca se guarda el token en claro, solo su hash SHA-256.

CREATE TABLE refresh_token (
    id bigint NOT NULL,
    token_hash character varying(64) NOT NULL,
    usuario_id bigint NOT NULL,
    expira_en timestamp(6) without time zone NOT NULL,
    revocado_en timestamp(6) without time zone,
    created_at timestamp(6) without time zone NOT NULL
);

ALTER TABLE refresh_token ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME refresh_token_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY refresh_token
    ADD CONSTRAINT refresh_token_pkey PRIMARY KEY (id);

ALTER TABLE ONLY refresh_token
    ADD CONSTRAINT uk_refresh_token_hash UNIQUE (token_hash);

ALTER TABLE ONLY refresh_token
    ADD CONSTRAINT fk_refresh_token_usuario FOREIGN KEY (usuario_id) REFERENCES usuario(id);

CREATE INDEX idx_refresh_token_usuario ON refresh_token (usuario_id);
